#!/bin/sh -e

exec >res/scroller.res

trap 'rm -f res/scroller.h res/scroller.res' EXIT

rm -rf res/scroller
mkdir res/scroller
convert scroller_1.png -crop 512x16 PNG8:res/scroller/%01d.png
for f in res/scroller/*.png; do
    n=$(basename $f .png)
    echo "IMAGE scroller_${n} \"scroller/${n}.png\" NONE"
done

trap '' EXIT
